---
title: CPU performance
order: 99
---

#### **Cause**: system cycle time
#### **Effect**: published performance

## Descriptive statistics
|       |     cause |    effect |
|:------|----------:|----------:|
| count | 209       | 209       |
| mean  |   4.74695 |   4.0372  |
| std   |   1.03789 |   1.04834 |
| min   |   2.83321 |   1.79176 |
| 25%   |   3.91202 |   3.29584 |
| 50%   |   4.70048 |   3.91202 |
| 75%   |   5.4161  |   4.72739 |
| max   |   7.31322 |   7.04752 |

## Scatter plot with marginals

```{=html}
<iframe width=600 height=500 src="plots/scatter_0100.html"></iframe>
```

## Time series plot (w/ index as timestep)

```{=html}
<iframe width=600 height=500 src="plots/series_0100.html"></iframe>
```

## Units
+----------+--------------------------+
| cause    | nanoseconds              |
+----------+--------------------------+
| effect   | relative benchmark value |
+----------+--------------------------+


## Citation
J. M. Mooij, J. Peters, D. Janzing, J. Zscheischler, B. Schoelkopf
"Distinguishing cause from effect using observational data: methods and benchmarks"
Journal of Machine Learning Research 17(32):1-102, 2016

## Original source
https://webdav.tuebingen.mpg.de/cause-effect/

## Original documentation
```
Dataset 'cpus' from the R MASS package. 

According to the description in the documentation of the package 
(https://cran.r-project.org/web/packages/MASS/MASS.pdf ):

"A relative performance measure and characteristics of 209 CPUs.

Source:
P. Ein-Dor and J. Feldmesser (1987) 
'Attributes of the performance of central processing units: a relative performance prediction model.'
Comm. ACM. 30, 308–317"

We converted the data to a text file by the following R commands:

library('MASS')
write.matrix(cpus,file='/tmp/cpus.txt',sep=',')

X = logarithm of the second column ('syct', cycle time in nanoseconds)
Y = logarithm of the seventh column ('perf', published performance on a benchmark mix relative to an IBM 370/158-3)

We consider syct to be one of the causes of perf.

Ground truth:  X -> Y
```

## dc_reflib's notes
::: {.callout-note title="Operational Causality"}
"Engineered" {{< fa robot >}}

The original data source is still available [here](https://cran.r-project.org/web/packages/MASS/), [here](https://cran.r-project.org/web/packages/MASS/MASS.pdf), or [here](https://www.stats.ox.ac.uk/pub/MASS4/). The original source focused on statistical, not _causal_, analysis. CPU cycle times, however, are often considered the primary driver of performance (see, e.g., [this article](https://performanceengineeringin.wordpress.com/2021/07/24/performance-understanding-cpu-time/)).
:::