---
title: DWD dataset \#1
order: 0
---

Bivariate 0001  [Tuebingen pair 0001]

#### **Cause**: altitude
#### **Effect**: temperature (average over 1961-1990)

## Descriptive statistics
|       |    cause |    effect |
|:------|---------:|----------:|
| count |  349     | 349       |
| mean  |  332.47  |   8.04155 |
| std   |  339.298 |   1.51851 |
| min   |    0     |  -4.8     |
| 25%   |   70     |   7.5     |
| 50%   |  255     |   8.3     |
| 75%   |  490     |   8.9     |
| max   | 2960     |  10.8     |

## Scatter plot with marginals

```{=html}
<iframe width=600 height=500 src="plots/scatter_0001.html"></iframe>
```

## Time series plot (w/ index as timestep)

```{=html}
<iframe width=600 height=500 src="plots/series_0001.html"></iframe>
```

## Units
+----------+-----------------+
| cause    | meters          |
+----------+-----------------+
| effect   | degrees Celsius |
+----------+-----------------+
{{< fa circle-exclamation >}} Units are just a guess. See notes below.

## Citation
Asuncion, A. & Newman, D.J. (2007).
UCI Machine Learning Repository [http://www.ics.uci.edu/~mlearn/MLRepository.html].
Irvine, CA: University of California, School of Information and Computer Science.

## Original source
https://webdav.tuebingen.mpg.de/cause-effect/

## Original documentation
```
Information for pairs0001:

DWD data (Deutscher Wetterdienst)

data was taken at 349 stations

taken from
http://www.dwd.de/bvbw/appmanager/bvbw/dwdwwwDesktop/?_nfpb=true&_pageLabel=_dwdwww_klima_umwelt_klimadaten_deutschland&T82002gsbDocumentPath=Navigation%2FOeffentlichkeit%2FKlima__Umwelt%2FKlimadaten%2Fkldaten__kostenfrei%2Fausgabe__mittelwerte__node.html__nnn%3Dtrue

more recent  link (Jan 2010):
http://www.dwd.de/bvbw/appmanager/bvbw/dwdwwwDesktop/?_nfpb=true&_pageLabel=_dwdwww_klima_umwelt_klimadaten_deutschland&T82002gsbDocumentPath=Navigation%2FOeffentlichkeit%2FKlima__Umwelt%2FKlimadaten%2Fkldaten__kostenfrei%2Fausgabe__mittelwerte__node.html__nnn%3Dtrue


x: altitude

y: temperature (average over 1961-1990)

ground truth:
x --> y

```

## dc_reflib's notes
The link to the original dataset appears to be dead, although the dwd.de site is still around. The units are reasonable guesses but cannot be confirmed without access to the original data.

::: {.callout-note title="Operational Causality"}
"Physics" {{< fa hand-sparkles >}} 

There is an empirical relationship between altitude and atmospheric temperature (see, e.g., [here](https://en.wikipedia.org/wiki/Atmospheric_temperature)) but it is dependent on other environmental factors. This data uses multi-decade time averages for the temperature measurements and includes no information regarding the altitude samples over that time period.
:::