---
title: Milking frequency and protein concentration
order: 84
---

#### **Cause**: time in-between measurements (from 1 to 14).
#### **Effect**: protein content of the milk 

## Descriptive statistics
|       |     cause |     effect |
|:------|----------:|-----------:|
| count | 994       | 994        |
| mean  |   7.5     |   3.40384  |
| std   |   4.03316 |   0.329512 |
| min   |   1       |   2.45     |
| 25%   |   4       |   3.18     |
| 50%   |   7.5     |   3.38     |
| 75%   |  11       |   3.61     |
| max   |  14       |   4.59     |

## Scatter plot with marginals

```{=html}
<iframe width=600 height=500 src="plots/scatter_0085.html"></iframe>
```

## Time series plot (w/ index as timestep)

```{=html}
<iframe width=600 height=500 src="plots/series_0085.html"></iframe>
```

## Units
+----------+-----------------+
| cause    | weeks           |
+----------+-----------------+
| effect   | percentage      |
+----------+-----------------+
{{< fa circle-exclamation >}} Units are just a guess. See notes below.


## Citation
J. M. Mooij, J. Peters, D. Janzing, J. Zscheischler, B. Schoelkopf
"Distinguishing cause from effect using observational data: methods and benchmarks"
Journal of Machine Learning Research 17(32):1-102, 2016

## Original source
https://webdav.tuebingen.mpg.de/cause-effect/

## Original documentation
```
Description of pair0085:

This data set is extracted from that for the milk protein trial used by Verbyla and Cullis (1990).  The original data set consists of assayed protein content of milk samples taken weekly from each of 79 cows.  The cows were randomly allocated to one of three diets: barley, mixed barley-lupins, and lupins, with 25, 27, and 27 cows in the three groups, respectively.  Measurements were taken for up to 19 weeks, but there were 38 drop-outs from week 15 onwards, corresponding to cows who stopped producing milk before the end of the experiment.

We removed the missing values (drop-outs) in the data set: we did not consider the measurements from week 15 onwards, which contain many drop-outs, and we discarded the cows with drop-outs before week 15.  Finally, the data set contains 71 cows and 14 weeks.  Furthermore, we re-organized the data set to see the relationship between the milk protein and the time to take the measurement:

X : time to take weekly measurements (from 1 to 14).

Y : protein content of the milk produced by each cow at time X.


Group truth: 

X -> Y.


Remark:

Here we do not consider the effect of the diets on the protein content.  Note that rigorously speaking, X, together with the diets, causes Y.

The original data set is available at
http://www.maths.lancs.ac.uk/Software/Oswald/


Reference:
A. P. Verbyla and B. R. CullisSource, "Modelling in Repeated Measures Experiments", Journal of the Royal Statistical Society. Series C (Applied Statistics), Vol. 39, No. 3(1990), pp. 341-356.
```

## dc_reflib's notes
::: {.callout-note title="Operational Causality"}
"Physics" {{< fa hand-sparkles >}} 

There is some evidence that more frequent milking of diary cows _might_ cause higher protein concentrations in their milk. See, e.g., [this article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6485445/) and [this meta-study](https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S2448-67602020000200003). The original data source is no longer available. 
:::