---
title: Stock returns (Hang Seng Bank and HSBC)
order: 60
---

#### **Cause**: stock returns of Hang Seng Bank (0011.HK)
#### **Effect**: stock return of HSBC Hldgs (0005.HK)

## Descriptive statistics
|       |          cause |         effect |
|:------|---------------:|---------------:|
| count | 1331           | 1331           |
| mean  |    0.000465943 |    0.000225431 |
| std   |    0.0131291   |    0.013797    |
| min   |   -0.0665152   |   -0.0857341   |
| 25%   |   -0.0058888   |   -0.00748879  |
| 50%   |    0           |    0           |
| 75%   |    0.00613299  |    0.00803387  |
| max   |    0.0667811   |    0.0625158   |

## Scatter plot with marginals

```{=html}
<iframe width=600 height=500 src="plots/scatter_0065.html"></iframe>
```

## Time series plot (w/ index as timestep)

```{=html}
<iframe width=600 height=500 src="plots/series_0065.html"></iframe>
```

## Units
+----------+-----------------+
| cause    | price           |
+----------+-----------------+
| effect   | price           |
+----------+-----------------+


## Citation
J. M. Mooij, J. Peters, D. Janzing, J. Zscheischler, B. Schoelkopf
"Distinguishing cause from effect using observational data: methods and benchmarks"
Journal of Machine Learning Research 17(32):1-102, 2016

## Original source
https://webdav.tuebingen.mpg.de/cause-effect/

## Original documentation
```
Information for pair0065:

Financial data:

x:	stock returns of Hang Seng Bank (0011.HK) 

y:	stock return of HSBC Hldgs (0005.HK) 

from Jan. 4, 2000 to Jun. 17, 2005. Data was obtained from the Yahoo finance database. HSBC owns about 60% of Hang Seng Bank.

Remark: We calculated the above returns from the raw data in the following way.
1. Extract the dividend/split adjusted closing price data from Yahoo Finance http://finance.yahoo.com/.
2. For the few days when the price is not available, we use simple linear interpolation to estimate the price.  Consequently the two time series are aligned.
3. For each stock, denote the closing price on day t by P_t, and the corresponding return is calculated by X_t = (P_t-P_{t-1 }) / P_{t-1 }.

ground truth:
x-->y
```

## dc_reflib's notes
Historical stock prices are still available on [Yahoo Finance](https://finance.yahoo.com/quote/HSBC?p=HSBC&.tsrc=fin-srch).

::: {.callout-note title="Operational Causality"}
"I don't know." {{< fa dumpster-fire >}} 

Causal relationships in stock markets are notoriously difficult to pin down. This research goes back to Granger and the beginnings of modern data causality research. Personally, I would take this implied causal relationship with a grain of salt. Here are some articles discussing stock market causality if you want to dive deeper: [Networks of causal relationships in the U.S. stock market](https://www.degruyter.com/document/doi/10.1515/demo-2022-0110/html?lang=en) and [Time-varying pattern causality inference in global stock markets](https://www.sciencedirect.com/science/article/abs/pii/S1057521921001423).
:::