---
title: (Young adult) spinal bone density and age
order: 87
---

#### **Cause**: age
#### **Effect**: spinal density

## Descriptive statistics
|       |    cause |       effect |
|:------|---------:|-------------:|
| count | 261      | 261          |
| mean  |  15.8661 |   0.0372276  |
| std   |   4.2955 |   0.0463963  |
| min   |   9.4    |  -0.0641026  |
| 25%   |  12.2    |   0.00524109 |
| 50%   |  15.3    |   0.026534   |
| 75%   |  19.15   |   0.0614514  |
| max   |  25.15   |   0.194464   |

## Scatter plot with marginals

```{=html}
<iframe width=600 height=500 src="plots/scatter_0088.html"></iframe>
```

## Time series plot (w/ index as timestep)

```{=html}
<iframe width=600 height=500 src="plots/series_0088.html"></iframe>
```

## Units
+----------+-----------------+
| cause    | years           |
+----------+-----------------+
| effect   | g/cm^2          |
+----------+-----------------+
{{< fa circle-exclamation >}} Units are just a guess. See notes below.


## Citation
J. M. Mooij, J. Peters, D. Janzing, J. Zscheischler, B. Schoelkopf
"Distinguishing cause from effect using observational data: methods and benchmarks"
Journal of Machine Learning Research 17(32):1-102, 2016

## Original source
https://webdav.tuebingen.mpg.de/cause-effect/

## Original documentation
```
x = age
y = Relative Spinal bone mineral density

Source:

"bone" data set from http://cran.r-project.org/web/packages/ElemStatLearn/ElemStatLearn.pdf

We obtained and preprocessed the data using the following R commands:

install.packages('ElemStatLearn')
library(ElemStatLearn)
boneuniq = bone[1,]
for( i in 2:dim(bone)[1] ) { 
  if( bone[i,1] != bone[i-1,1] ) { 
    boneuniq <- rbind(boneuniq,bone[i,])
  } 
}
write.table(boneuniq[,c(2,4)],file='/tmp/bone.csv',row.names=FALSE,col.names=FALSE)
remove.packages('ElemStatLearn')

For the preprocessing, we only take the first measurement for each child, and 
selected only the columns "age" and "spnbmd" (Relative Change in Spinal BMD).

The ground truth should be that age causes relative change in spinal BMD.
```

## dc_reflib's notes
::: {.callout-note title="Operational Causality"}
"I don't know." {{< fa dumpster-fire >}} 

The original dataset has been removed from CRAN (but archives of past version [are still available](https://cran.r-project.org/web/packages/ElemStatLearn/)). Spinal bone density increases in children based on a [collection of causal factors](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3527676/) and then remains roughly constant until later stages of life. See, e.g., [this study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2413314/). It is unclear why this dataset purports spinal bone density should change (causally or otherwise) for young adults as they age.
:::